apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  #labels:
  #  app.kubernetes.io/name: {{ include "helloworld.name" . }}
  #  helm.sh/chart: {{ include "helloworld.chart" . }}
  #  app.kubernetes.io/instance: {{ .Release.name }}
  #  app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: helloworld
