# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
image:
  repository: "helloworld"
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1"
service:
  type: NodePort
  port: 80